### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by labrax** [pepe78/POPC-examples#1]
Hi Peter,

Thank you for sharing your project with us, the images are very nice.

I have interest in applying your clustering approach, however I am afraid I cannot do the transformation to Python, which is my workflow. Would you happen to know if there is a Python implementation of this project? Would you suggest me alternatives?

Best wishes,

**Comment by pepe78** [comment]
I currently do not have code for this project in python, but you can always connect with ModuleQ (https://moduleq.com/company-about) company, which does have source code in python as python implementation & research was done during work there.

**Comment by pepe78** [comment]
Now, I added implementation also in Python:
https://github.com/pepe78/POPC-examples-python

Cheers!
